package entitypackage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller    //this means that this class is a Controller
@RequestMapping(path = "/web") // URL's start with /web
public class MainController {
    @Autowired  // this means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

//    @GetMapping(path = "/add")
//    public @ResponseBody String showDataFromDB (@RequestParam String name, @RequestParam String email){
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        UserEntity userEntity = new UserEntity();
//        //userEntity.getName(); // from DB ?
//        //userEntity.getEmail(); // from DB ?
//        System.out.println(userEntity.getName());
//        System.out.println(userEntity.getEmail());
//        return ""
//    }

    @GetMapping(path = "/read")
    public @ResponseBody Iterable<UserEntity> getAllUsers(){

        return userRepository.findAll();

    }


}