INSERT INTO USERS(ID, NAME, SURNAME, COMPANY_ID)
values(IFNULL((SELECT MAX(ID) FROM USERS),0)+1, 'name1', 'surname1', 1);

INSERT INTO USERS(ID, NAME, SURNAME, COMPANY_ID)
values(IFNULL((SELECT MAX(ID) FROM USERS),0)+1, 'name1', 'surname1', 1);